version: "3.8"

x-mongo:
  &default-mongo
  image: mongo:6.0.3
  restart: always

services:
  first-config:
    << : *default-mongo
    hostname: first-config
    command: mongod --configsvr --replSet configReplicaSet --bind_ip localhost,first-config
  second-config:
    << : *default-mongo
    hostname: second-config
    command: mongod --configsvr --replSet configReplicaSet --bind_ip localhost,second-config
  third-config:
    << : *default-mongo
    hostname: third-config
    command: mongod --configsvr --replSet configReplicaSet --bind_ip localhost,third-config
  config-init:
    << : *default-mongo
    restart: "no"
    depends_on:
      - first-config
      - second-config
      - third-config
    command: >
      sh -c "sleep 15 &&
             mongosh --host first-config --port 27019 --eval 'rs.initiate({_id:\"configReplicaSet\",configsvr:true,members:[{_id:0,host:\"first-config:27019\"},{_id:1,host:\"second-config:27019\"},{_id:2,host:\"third-config:27019\"}]})'"
  mongos:
    << : *default-mongo
    hostname: mongos
    ports:
      - 27017:27017
    volumes:
      - ./mongos:/root
    command: >
      sh -c "sleep 30 &&
             mongos --pidfilepath /root/mongos.pid --bind_ip 0.0.0.0 --configdb configReplicaSet/first-config:27019,second-config:27019,third-config:27019"
