version: "3.8"

x-mongo:
  &default-mongo
  image: mongo:6.0.3
  restart: always

services:
  # config
  first-config:
    << : *default-mongo
    hostname: first-config
    volumes:
      - ./workspace/mongod/first-config:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --configsvr --keyFile /mongos/replkey --replSet configReplicaSet --bind_ip localhost,first-config
  second-config:
    << : *default-mongo
    hostname: second-config
    volumes:
      - ./workspace/mongod/second-config:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --configsvr --keyFile /mongos/replkey --replSet configReplicaSet --bind_ip localhost,second-config
  third-config:
    << : *default-mongo
    hostname: third-config
    volumes:
      - ./workspace/mongod/third-config:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --configsvr --keyFile /mongos/replkey --replSet configReplicaSet --bind_ip localhost,third-config
  # shard-one
  first-shard-one:
    << : *default-mongo
    hostname: first-shard-one
    volumes:
      - ./workspace/mongod/first-shard-one:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --shardsvr --keyFile /mongos/replkey --replSet oneReplicaSet --bind_ip localhost,first-shard-one
  second-shard-one:
    << : *default-mongo
    hostname: second-shard-one
    volumes:
      - ./workspace/mongod/second-shard-one:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --shardsvr --keyFile /mongos/replkey --replSet oneReplicaSet --bind_ip localhost,second-shard-one
  third-shard-one:
    << : *default-mongo
    hostname: third-shard-one
    volumes:
      - ./workspace/mongod/third-shard-one:/data/db
      - ./workspace/mongos:/mongos
    command: mongod --shardsvr --keyFile /mongos/replkey --replSet oneReplicaSet --bind_ip localhost,third-shard-one
  mongos:
    << : *default-mongo
    hostname: mongos
    ports:
      - 27017:27017
    volumes:
      - ./workspace/mongos:/mongos
    command: >
      sh -c "
        sleep 30;
        mongos --keyFile /mongos/replkey --pidfilepath /mongos/mongos.pid --bind_ip 0.0.0.0 --configdb configReplicaSet/first-config:27019,second-config:27019,third-config:27019;
      "
